// Generated by https://quicktype.io

import { IStorehouseRequestUtility } from "./IAlmacen.interface";

export interface IRequestStoreHouseResponse {
  data: Data;
  ok: boolean;
}

export interface IRequestStoreHouseDataResponse {
  data: StorehouseRequestData;
  ok: boolean;
}

export interface Data {
  requests: Request[];
}

export interface StorehouseRequestData {
  request: RequestWithUtilities;
}

export interface Request {
  id: string;
  user_id: string;
  user: User;
  folio: number;
  status_id: string;
  status: Status;
  utilities: null;
  created_at: string;
  updated_at: string;
}

export interface RequestWithUtilities {
  id: string;
  user_id: string;
  user: User;
  folio: number;
  status_id: string;
  status: Status;
  utilities: IStorehouseRequestUtility[];
  created_at: string;
  updated_at: string;
}

export interface Status {
  id: string;
  name: string;
}

export interface User {
  id: string;
  role_id: string;
  role: Status;
  name: string;
  surname: string;
  full_name: string;
  deleted_at: string;
}
